In [1]:
# code to make bankruptcy prediction in 2022

In [1]:
#!pip install wrds
import wrds

In [2]:
conn = wrds.Connection()
# tjxviY3JA3p@tEx is the password

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
Loading library list...
Done

In [ ]:
conn.list_libraries()

In [3]:
bankruptcies = conn.raw_sql("select * from  wrdssec_all.items8k where nitem = '1.03'")
# get bankruptcies filed starting in 2004
bankruptcies['cik'].nunique()
# 1759 companies captured
# WILL NEED TO CLEAN SO THAT WE MAKE SURE EACH ONE IS EITHER COMING OUT OF OR ENTERING ACTUAL BANKRUPTCY

1759

In [4]:
companies = conn.raw_sql("""
    SELECT *
    FROM wrdsapps_finratio.firm_ratio a
    INNER JOIN wrdssec_common.wciklink_gvkey b ON a.gvkey = b.gvkey
    WHERE a.public_date <= '2021-12-31' and a.public_date>='2003-01-01'
""")

In [5]:
companies.head(30)

,gvkey,permno,adate,qdate,public_date,capei,be,bm,evm,pe_op_basic,...,n10k,n10k_nt,n10k_a,n10q,n10q_nt,n10q_a,ndef,n8k,ntot,flag
0,001004,54594.0,2002-05-31,2002-11-30,2003-01-31,11.456062,334.350,1.909082,19.541750,-14.424242,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
1,001004,54594.0,2002-05-31,2002-11-30,2003-02-28,10.709973,334.350,1.909082,19.541750,-13.484848,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
2,001004,54594.0,2002-05-31,2002-11-30,2003-03-31,9.097460,334.350,1.909082,19.541750,-11.454545,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
3,001004,54594.0,2002-05-31,2003-02-28,2003-04-30,10.986958,337.447,2.380798,15.537082,-16.869565,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
4,001004,54594.0,2002-05-31,2003-02-28,2003-05-31,12.742605,337.447,2.380798,15.537082,-19.565217,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,001004,54594.0,2010-05-31,2010-08-31,2010-12-31,19.866488,818.353,1.343272,10.679079,19.076389,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
96,001004,54594.0,2010-05-31,2010-11-30,2011-01-31,18.877201,840.789,0.862798,11.176954,17.625000,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
97,001004,54594.0,2010-05-31,2010-11-30,2011-02-28,19.229519,840.789,0.862798,11.176954,17.953947,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
98,001004,54594.0,2010-05-31,2010-11-30,2011-03-31,19.563033,840.789,0.862798,11.176954,18.236842,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0
99,001004,54594.0,2010-05-31,2011-02-28,2011-04-30,17.867287,874.279,0.806115,10.716341,15.975460,...,29.0,0.0,0.0,89.0,0.0,2.0,37.0,242.0,1980.0,3.0

In [6]:
companies['gvkey'].nunique()

gvkey    9319
gvkey    9319
dtype: int64